// src/app/not-found.tsx
import Link from 'next/link'

export default function NotFound() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-cream px-4">
      <div className="text-center max-w-md">
        <p className="font-cormorant text-8xl font-semibold text-lavender mb-4">404</p>
        <h1 className="font-cormorant text-4xl font-semibold text-plum mb-4">
          Page not found
        </h1>
        <p className="text-plum/60 mb-8">
          The page you&apos;re looking for doesn&apos;t exist or has been moved.
        </p>
        <Link
          href="/products"
          className="inline-block px-8 py-3 bg-lavender text-white rounded-full text-sm font-medium hover:bg-lavender/90 transition-colors"
        >
          Shop our fragrances
        </Link>
      </div>
    </div>
  )
}

// src/app/pages/not-found/not-found.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="min-h-screen bg-cream flex items-center justify-center px-4">
      <div class="text-center space-y-6">
        <p class="font-display text-[8rem] font-semibold text-cream-dark leading-none">404</p>
        <h1 class="font-display text-4xl font-semibold text-plum">Page Not Found</h1>
        <p class="font-body text-muted max-w-sm mx-auto">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div class="flex gap-4 justify-center">
          <a routerLink="/" class="btn-primary">Go Home</a>
          <a routerLink="/products" class="btn-outline">Browse Products</a>
        </div>
      </div>
    </div>
  `,
})
export class NotFoundComponent {}
