// src/components/home/HeroSection.tsx
'use client'

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'

const stats = [
  { value: '120+', label: 'Days Lasting' },
  { value: '3', label: 'Signature Scents' },
  { value: '100%', label: 'Alcohol-Free' },
  { value: '🍁', label: 'Made in Canada' },
]

export default function HeroSection() {
  return (
    <section>
      {/* ── Full-width banner ──────────────────────────────── */}
      <div className="relative min-h-[88vh] flex items-center overflow-hidden">
        {/* Banner background image */}
        <Image
          src="/images/banner_image.png"
          alt="BlossomRays botanical car air fresheners"
          fill
          className="object-cover object-center"
          priority
          sizes="100vw"
        />

        {/* Gradient overlay — dark left, fades right */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#080808]/95 via-[#0d0d0d]/75 to-[#0d0d0d]/25" />
        {/* Bottom fade */}
        <div className="absolute inset-0 bg-gradient-to-t from-[#080808]/70 via-transparent to-transparent" />

        {/* Content */}
        <div className="relative z-10 w-full max-w-7xl mx-auto px-6 sm:px-10 lg:px-14 py-24">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.25, 0.46, 0.45, 0.94] }}
            className="max-w-[540px] space-y-7"
          >
            {/* Badge */}
            <div className="inline-flex items-center gap-2 border border-gold/40 bg-gold/10 backdrop-blur-sm px-4 py-2 rounded-full">
              <span className="w-1.5 h-1.5 rounded-full bg-gold animate-pulse flex-shrink-0" />
              <span className="font-body text-[10px] font-semibold tracking-[0.22em] uppercase text-gold">
                New Season · Limited Offer
              </span>
            </div>

            {/* Headline */}
            <h1 className="font-display text-[3.2rem] sm:text-[4rem] xl:text-[5rem] font-semibold text-white leading-[1.04]">
              Elevate<br />
              <em className="italic" style={{ color: '#E8A8A0' }}>Every Drive</em>
            </h1>

            {/* Sub copy */}
            <p className="font-body text-white/55 text-[15px] sm:text-base leading-relaxed max-w-[380px]">
              Premium botanical car air fresheners — alcohol-free, handcrafted in Canada.
              Lavender, Rose &amp; Millennium. Lasting 120+ days.
            </p>

            {/* Price */}
            <div className="flex items-baseline gap-3">
              <span className="font-body text-[11px] uppercase tracking-[0.18em] text-white/35">From</span>
              <span className="font-display text-3xl font-semibold text-gold">$17.99</span>
            </div>

            {/* CTAs */}
            <div className="flex flex-wrap items-center gap-4 pt-1">
              <Link
                href="/products"
                className="inline-flex items-center gap-2 bg-gold hover:bg-gold/90 text-white font-body text-[11px] font-semibold tracking-[0.18em] uppercase px-8 py-4 rounded-full transition-all duration-200 shadow-lg shadow-gold/20"
              >
                Shop Collection
              </Link>
              <a
                href="#collection"
                className="font-body text-[11px] font-medium tracking-[0.18em] uppercase text-white/45 hover:text-gold transition-colors duration-200"
              >
                Explore Scents ↓
              </a>
            </div>
          </motion.div>
        </div>
      </div>

      {/* ── Stats strip ────────────────────────────────────── */}
      <div className="bg-[#0d0d0d] border-t border-white/[0.06]">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 sm:grid-cols-4 divide-x divide-white/[0.07]">
            {stats.map(({ value, label }) => (
              <div key={label} className="flex flex-col items-center py-5 gap-1.5">
                <span className="font-display text-[2.2rem] font-semibold text-gold leading-none">
                  {value}
                </span>
                <span className="font-body text-[11px] font-semibold tracking-[0.16em] uppercase text-white/50">
                  {label}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

// src/app/components/home/hero-section.component.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';

const slides = [
  {
    image: '/images/banner_image.png',
    badge: 'New Season · Limited Offer',
    headline: ['Elevate', 'Every Drive'],
    accentLine: 1,
    sub: 'Premium botanical car air fresheners — alcohol-free, handcrafted in Canada. Lavender, Rose & Millennium. Lasting 120+ days.',
    cta: { label: 'Shop Collection', href: '/products' },
  },
  {
    image: '/images/banner_image.png',
    badge: 'Signature Scent · Rose',
    headline: ['Bloom', 'On the Road'],
    accentLine: 1,
    sub: 'Bulgarian rose · peony · soft musk. Romance in every mile.',
    cta: { label: 'Shop Rose', href: '/products/rose-car-air-freshener' },
  },
  {
    image: '/images/banner_image.png',
    badge: 'Signature Scent · Lavender',
    headline: ['Calm', 'Your Commute'],
    accentLine: 1,
    sub: 'French lavender · bergamot · cedarwood. Serenity from the first breath.',
    cta: { label: 'Shop Lavender', href: '/products/lavender-car-air-freshener' },
  },
];

const stats = [
  { value: '120+', label: 'Days Lasting' },
  { value: '3', label: 'Signature Scents' },
  { value: '100%', label: 'Alcohol-Free' },
  { value: '🍁', label: 'Made in Canada' },
];

@Component({
  selector: 'app-hero-section',
  standalone: true,
  imports: [RouterLink, CommonModule],
  template: `
    <section>
      <!-- Carousel banner -->
      <div
        class="relative h-[60vh] overflow-hidden"
        (mouseenter)="paused = true"
        (mouseleave)="paused = false"
      >
        <!-- Image -->
        <div class="absolute inset-0 transition-opacity duration-700">
          <img
            [src]="current().image"
            [alt]="current().badge"
            class="w-full h-full object-cover object-center"
          />
        </div>

        <!-- Overlays -->
        <div class="absolute inset-0 bg-gradient-to-r from-[#080808]/95 via-[#0d0d0d]/75 to-[#0d0d0d]/25"></div>
        <div class="absolute inset-0 bg-gradient-to-t from-[#080808]/70 via-transparent to-transparent"></div>

        <!-- Content -->
        <div class="relative z-10 h-full flex items-center">
          <div class="w-full max-w-7xl mx-auto px-6 sm:px-10 lg:px-14">
            <div class="max-w-xl space-y-5">
              <!-- Badge -->
              <span class="inline-block font-body text-[10px] font-semibold tracking-[0.28em] uppercase text-gold/90 border border-gold/40 px-3 py-1">
                {{ current().badge }}
              </span>

              <!-- Headline -->
              <h1 class="font-display font-semibold text-white leading-none">
                <span
                  *ngFor="let line of current().headline; let i = index"
                  class="block"
                  [class.text-gold]="i === current().accentLine"
                  [ngStyle]="{ fontSize: 'clamp(1.8rem, 4vw, 3rem)' }"
                >{{ line }}</span>
              </h1>

              <!-- Sub -->
              <p class="font-body text-[15px] text-white/60 leading-relaxed max-w-md">
                {{ current().sub }}
              </p>

              <!-- CTA -->
              <a
                [routerLink]="current().cta.href"
                class="btn-primary inline-flex"
              >
                {{ current().cta.label }}
                <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"/>
                </svg>
              </a>
            </div>
          </div>
        </div>

        <!-- Slide indicators -->
        <div class="absolute bottom-6 left-1/2 -translate-x-1/2 flex gap-2 z-10">
          <button
            *ngFor="let s of slides; let i = index"
            (click)="setCurrent(i)"
            [class]="i === currentIndex() ? 'w-6 h-1.5 bg-gold' : 'w-1.5 h-1.5 bg-white/40 hover:bg-white/70'"
            class="transition-all duration-300 rounded-full"
            [attr.aria-label]="'Slide ' + (i + 1)"
          ></button>
        </div>

        <!-- Arrow controls -->
        <button
          (click)="prev()"
          class="absolute left-4 top-1/2 -translate-y-1/2 z-10 w-10 h-10 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white transition-colors"
          aria-label="Previous slide"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5"/>
          </svg>
        </button>
        <button
          (click)="next()"
          class="absolute right-4 top-1/2 -translate-y-1/2 z-10 w-10 h-10 flex items-center justify-center bg-white/10 hover:bg-white/20 text-white transition-colors"
          aria-label="Next slide"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5"/>
          </svg>
        </button>
      </div>

      <!-- Stats bar -->
      <div class="bg-white border-b border-cream-dark">
        <div class="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 divide-x divide-cream-dark">
          <div *ngFor="let stat of stats" class="flex flex-col items-center py-6 gap-0.5">
            <span class="font-display text-2xl font-semibold text-plum">{{ stat.value }}</span>
            <span class="font-body text-[11px] tracking-[0.12em] uppercase text-muted">{{ stat.label }}</span>
          </div>
        </div>
      </div>
    </section>
  `,
})
export class HeroSectionComponent implements OnInit, OnDestroy {
  readonly slides = slides;
  readonly stats = stats;
  readonly currentIndex = signal(0);
  readonly current = signal(slides[0]);
  paused = false;
  private intervalId?: ReturnType<typeof setInterval>;

  ngOnInit(): void {
    this.intervalId = setInterval(() => {
      if (!this.paused) this.next();
    }, 5000);
  }

  ngOnDestroy(): void {
    clearInterval(this.intervalId);
  }

  next(): void {
    const idx = (this.currentIndex() + 1) % slides.length;
    this.currentIndex.set(idx);
    this.current.set(slides[idx]);
  }

  prev(): void {
    const idx = (this.currentIndex() - 1 + slides.length) % slides.length;
    this.currentIndex.set(idx);
    this.current.set(slides[idx]);
  }

  setCurrent(idx: number): void {
    this.currentIndex.set(idx);
    this.current.set(slides[idx]);
  }
}
