// src/app/(auth)/register/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/client'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Card from '@/components/ui/Card'

const RegisterSchema = z.object({
  full_name: z.string().min(2, 'Full name is required'),
  email: z.string().email('Enter a valid email'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  confirm_password: z.string(),
}).refine((d) => d.password === d.confirm_password, {
  message: "Passwords don't match",
  path: ['confirm_password'],
})
type RegisterForm = z.infer<typeof RegisterSchema>

export default function RegisterPage() {
  const router = useRouter()
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<RegisterForm>({ resolver: zodResolver(RegisterSchema) })

  const onSubmit = async ({ email, password, full_name }: RegisterForm) => {
    setError(null)
    const supabase = createClient()
    const { error: authError } = await supabase.auth.signUp({
      email,
      password,
      options: { data: { full_name } },
    })

    if (authError) {
      setError(authError.message)
      return
    }

    setSuccess(true)
  }

  if (success) {
    return (
      <Card padding="lg" hover={false}>
        <div className="text-center space-y-4">
          <span className="text-5xl">✉️</span>
          <h2 className="font-display text-2xl font-semibold text-plum">Check Your Email</h2>
          <p className="font-body text-muted text-sm">
            We&apos;ve sent a confirmation link to your email. Click it to activate your account.
          </p>
          <Link href="/login">
            <Button variant="outline" className="mt-2">Back to Login</Button>
          </Link>
        </div>
      </Card>
    )
  }

  return (
    <Card padding="lg" hover={false}>
      <div className="space-y-6">
        <div className="text-center">
          <Link href="/" className="font-display text-2xl font-semibold italic text-plum">
            BlossomRays
          </Link>
          <h1 className="font-display text-3xl font-semibold text-plum mt-4">Create Account</h1>
          <p className="font-body text-muted text-sm mt-1">Join the BlossomRays community</p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <Input label="Full Name" placeholder="Jane Smith" error={errors.full_name?.message} {...register('full_name')} />
          <Input label="Email" type="email" placeholder="you@example.com" error={errors.email?.message} {...register('email')} />
          <Input label="Password" type="password" placeholder="Min. 8 characters" error={errors.password?.message} {...register('password')} />
          <Input label="Confirm Password" type="password" placeholder="••••••••" error={errors.confirm_password?.message} {...register('confirm_password')} />

          {error && (
            <p className="text-sm font-body text-red-600 bg-red-50 px-4 py-2.5 rounded-xl border border-red-200">
              {error}
            </p>
          )}

          <Button type="submit" className="w-full" size="lg" loading={isSubmitting}>
            Create Account
          </Button>
        </form>

        <p className="text-center font-body text-sm text-muted">
          Already have an account?{' '}
          <Link href="/login" className="text-lavender-dark font-medium hover:underline">
            Sign in
          </Link>
        </p>
      </div>
    </Card>
  )
}

// src/app/pages/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [RouterLink, CommonModule, ReactiveFormsModule],
  template: `
    <div class="min-h-screen bg-cream flex items-center justify-center px-4 py-16">
      <div class="w-full max-w-md">
        <div class="bg-white border border-cream-dark p-8 space-y-6">
          <div class="text-center">
            <a routerLink="/" class="font-display text-2xl font-semibold italic text-plum">BlossomRays</a>
            <h1 class="font-display text-3xl font-semibold text-plum mt-4">Create Account</h1>
            <p class="font-body text-muted text-sm mt-1">Join the BlossomRays community</p>
          </div>

          <ng-container *ngIf="!success()">
            <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
              <div>
                <label class="block font-body text-[11px] uppercase tracking-widest text-muted mb-1.5">Full Name</label>
                <input formControlName="full_name" type="text" placeholder="Jane Smith" class="input-field"
                  [class.border-red-400]="fieldInvalid('full_name')" />
                <p *ngIf="fieldInvalid('full_name')" class="font-body text-xs text-red-500 mt-1">Name is required</p>
              </div>

              <div>
                <label class="block font-body text-[11px] uppercase tracking-widest text-muted mb-1.5">Email</label>
                <input formControlName="email" type="email" placeholder="you@example.com" class="input-field"
                  [class.border-red-400]="fieldInvalid('email')" />
                <p *ngIf="fieldInvalid('email')" class="font-body text-xs text-red-500 mt-1">Valid email required</p>
              </div>

              <div>
                <label class="block font-body text-[11px] uppercase tracking-widest text-muted mb-1.5">Password</label>
                <input formControlName="password" type="password" placeholder="••••••••" class="input-field"
                  [class.border-red-400]="fieldInvalid('password')" />
                <p *ngIf="fieldInvalid('password')" class="font-body text-xs text-red-500 mt-1">Minimum 8 characters</p>
              </div>

              <div *ngIf="error()" class="bg-red-50 border border-red-200 text-red-600 px-4 py-2.5 font-body text-sm">
                {{ error() }}
              </div>

              <button type="submit" [disabled]="loading()" class="btn-primary w-full">
                {{ loading() ? 'Creating Account...' : 'Create Account' }}
              </button>
            </form>
          </ng-container>

          <ng-container *ngIf="success()">
            <div class="text-center space-y-4 py-4">
              <div class="text-5xl">📧</div>
              <p class="font-body text-plum font-medium">Check your email!</p>
              <p class="font-body text-sm text-muted">We've sent a confirmation link to your inbox. Click it to activate your account.</p>
            </div>
          </ng-container>

          <p class="font-body text-sm text-center text-muted">
            Already have an account?
            <a routerLink="/login" class="text-plum hover:text-gold transition-colors ml-1">Sign In</a>
          </p>
        </div>
      </div>
    </div>
  `,
})
export class RegisterComponent {
  private readonly auth = inject(AuthService);
  private readonly fb = inject(FormBuilder);

  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  readonly success = signal(false);

  readonly form = this.fb.group({
    full_name: ['', [Validators.required, Validators.minLength(2)]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
  });

  fieldInvalid(field: string): boolean {
    const ctrl = this.form.get(field);
    return !!(ctrl?.invalid && ctrl?.touched);
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.error.set(null);

    const { email, password, full_name } = this.form.value;
    const err = await this.auth.signUp(email!, password!, full_name!);
    if (err) {
      this.error.set(err);
    } else {
      this.success.set(true);
    }
    this.loading.set(false);
  }
}
